sudo: required
language: java
jdk: oraclejdk8

before_install:
  - sh travis_prepare.sh
  - cd app/Biometrics/Java/enroll-finger-from-scanner

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
 - gradle checkstyleMain
 - gradle test jacocoTestCoverageVerification
notifications:
  slack:
    secure: ADxaIcZY6IxbieA/SPLMIYA7elOtHVMZSfGmOLqzHSGqbxr4PsR2da1+QIogslkbhJx4Eki0bTAbLGWJiOXSKIWjT5tRWpVNV52L0pvYBXWbeKJrmomjnv4nglzNc4qdfspw2gONCzQ532LxnyCOXGfbFwP/QACZ9uOmtcS6ki/zeAke8BlU//zQ5uc8LBC0AajFuk/PrK0bHDMtGjKpimDV8tn/NqCt5JggkkTMGV5C85vlsNHmWjN0S7wKqUbq5yIZ6MGrMp7+9+ljWDxTkZh6m91Uo6EIJII1/MDYCpqY/zz9ZIxnMB839G8gJL8VDzJuYuqNuv0S3tlCT8QEc/EVvJ197ftGQJC9I51Ak1fmaxc169Nf4dykJ7ME6SQKaI+lQffW8R5IXYOgFp8BRX8di2MRHJ6hE+mZKl2PkgCqWI2/1Gu+1yZm+30Zt17VN3SAyHUdSUzqLuAgPuP08B59a4ABkV500iNWq5qQvlvtFq0ucNY9SJfazz++Pzn7x/MepbHlOkPwdHiXC9ZNd8tCfGiWigPUxix3Gjxd2ea3lkfE/LJJ0Vbj4eYWk1y6AQiuh2otkrPmTTe8zwWTGEOV20ZDBOtHnhSZu0rjESizio+B/1ZfXPROTiEC+w6JF1Pz3jzjgHdmopk/FcYs6r9VPyMGoHvzCu8HNtkpx28=
